export const guitarSources = {
  8: require("../../assets/audio/guitar/8.wav"),
  9: require("../../assets/audio/guitar/9.wav"),
  10: require("../../assets/audio/guitar/10.wav"),
  11: require("../../assets/audio/guitar/11.wav"),
  12: require("../../assets/audio/guitar/12.wav"),
  13: require("../../assets/audio/guitar/13.wav"),
  14: require("../../assets/audio/guitar/14.wav"),
  15: require("../../assets/audio/guitar/15.wav"),
  16: require("../../assets/audio/guitar/16.wav"),
  17: require("../../assets/audio/guitar/17.wav"),
  18: require("../../assets/audio/guitar/18.wav"),
  19: require("../../assets/audio/guitar/19.wav"),
  20: require("../../assets/audio/guitar/20.wav"),
  21: require("../../assets/audio/guitar/21.wav"),
  22: require("../../assets/audio/guitar/22.wav"),
  23: require("../../assets/audio/guitar/23.wav"),
  24: require("../../assets/audio/guitar/24.wav"),
  25: require("../../assets/audio/guitar/25.wav"),
  26: require("../../assets/audio/guitar/26.wav"),
  27: require("../../assets/audio/guitar/27.wav"),
  28: require("../../assets/audio/guitar/28.wav"),
  29: require("../../assets/audio/guitar/29.wav"),
  30: require("../../assets/audio/guitar/30.wav"),
  31: require("../../assets/audio/guitar/31.wav"),
  32: require("../../assets/audio/guitar/32.wav"),
};

export const drumSources = {
  click: require("../../assets/audio/drums/click.wav"),
  kick: require("../../assets/audio/drums/kick.wav"),
  snare: require("../../assets/audio/drums/snare.wav"),
  hat: require("../../assets/audio/drums/hat.wav"),
};
